apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: pull-secret-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: runtimes-inventory-operator
    app.kubernetes.io/part-of: runtimes-inventory-operator
    app.kubernetes.io/managed-by: kustomize
  name: pull-secret-rolebinding
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pull-secret-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
